services:
  - type: web
    name: qr-chaos
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --timeout 0
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.5
